"use strict";

import mongoose from "mongoose";
import Product from "../models/product.js";
import Category from "../models/category.js";
import Image from "../models/image.js";

const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI || process.env.MONGODB_URI || "mongodb://127.0.0.1:27017/node_fulltask");
    console.log("✅ MongoDB connected");
  } catch (error) {
    console.error("❌ MongoDB connection error:", error);
    process.exit(1);
  }
};

const seedData = async () => {
  try {
    console.log("🗑️  Đang xóa dữ liệu cũ...");
    await Product.deleteMany({});
    await Category.deleteMany({});
    await Image.deleteMany({});

    // Tạo Categories
    console.log("📁 Đang tạo categories...");
    const categoriesData = [
      { name: "Món chính", slug: "mon-chinh", description: "Các món ăn chính", isActive: true },
      { name: "Khai vị", slug: "khai-vi", description: "Món khai vị", isActive: true },
      { name: "Tráng miệng", slug: "trang-mieng", description: "Món tráng miệng", isActive: true },
      { name: "Đồ uống", slug: "do-uong", description: "Nước uống các loại", isActive: true },
      { name: "Salad", slug: "salad", description: "Salad tươi ngon", isActive: true },
    ];
    const categories = await Category.insertMany(categoriesData);

    // Tạo Images với Unsplash URLs
    console.log("🖼️  Đang tạo images...");
    const imagesData = [
      { url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800", alt: "Salad tươi" },
      { url: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800", alt: "Pizza" },
      { url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800", alt: "Burger" },
      { url: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800", alt: "Món ăn" },
      { url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800", alt: "Bữa sáng" },
      { url: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800", alt: "Pancakes" },
      { url: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800", alt: "Salad bát" },
      { url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800", alt: "Healthy" },
      { url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800", alt: "Pasta" },
      { url: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=800", alt: "Sushi" },
      { url: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800", alt: "Cocktail" },
      { url: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=800", alt: "Smoothie" },
      { url: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800", alt: "Dessert" },
      { url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800", alt: "Soup" },
      { url: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800", alt: "Steak" },
    ];
    const images = await Image.insertMany(imagesData);

    // Dữ liệu sản phẩm thực tế
    console.log("🍔 Đang tạo products...");
    
    const productsData = [
      // MÓN CHÍNH - Best sellers
      {
        name: "Bò bít tết Úc cao cấp",
        description: "Thịt bò Úc nhập khẩu, nướng chín vừa, phục vụ kèm khoai tây nghiền và rau củ",
        price: 450000,
        categoryId: categories[0]._id,
        listProductImage: [images[14]._id],
        stock: 25,
        status: "available",
        preparationTime: "25-30 phút",
        calories: 680,
        rating: 4.8,
        reviewCount: 245,
        viewCount: 5200,
        soldCount: 680,
        discount: 0,
      },
      {
        name: "Cơm gà Hải Nam",
        description: "Gà luộc mềm, cơm thơm béo, nước chấm đậm đà",
        price: 85000,
        categoryId: categories[0]._id,
        listProductImage: [images[4]._id],
        stock: 50,
        status: "available",
        preparationTime: "20-25 phút",
        calories: 520,
        rating: 4.7,
        reviewCount: 389,
        viewCount: 8500,
        soldCount: 1250,
        discount: 15,
      },
      {
        name: "Spaghetti Carbonara",
        description: "Mì Ý sốt kem trứng, thịt xông khói giòn",
        price: 120000,
        categoryId: categories[0]._id,
        listProductImage: [images[8]._id],
        stock: 35,
        status: "available",
        preparationTime: "15-20 phút",
        calories: 580,
        rating: 4.6,
        reviewCount: 312,
        viewCount: 6800,
        soldCount: 890,
        discount: 20,
      },
      {
        name: "Burger bò phô mai đặc biệt",
        description: "Bánh mì tự làm, thịt bò Wagyu, phô mai Cheddar tan chảy",
        price: 165000,
        categoryId: categories[0]._id,
        listProductImage: [images[2]._id],
        stock: 40,
        status: "available",
        preparationTime: "18-22 phút",
        calories: 720,
        rating: 4.9,
        reviewCount: 456,
        viewCount: 9200,
        soldCount: 1580,
        discount: 10,
      },
      {
        name: "Pizza Margherita",
        description: "Pizza truyền thống Ý với cà chua tươi, phô mai Mozzarella",
        price: 180000,
        categoryId: categories[0]._id,
        listProductImage: [images[1]._id],
        stock: 30,
        status: "available",
        preparationTime: "22-25 phút",
        calories: 640,
        rating: 4.7,
        reviewCount: 278,
        viewCount: 7100,
        soldCount: 920,
        discount: 25,
      },
      {
        name: "Sushi combo đặc biệt",
        description: "12 miếng sushi cá hồi, cá ngừ tươi sống",
        price: 320000,
        categoryId: categories[0]._id,
        listProductImage: [images[9]._id],
        stock: 20,
        status: "available",
        preparationTime: "20-25 phút",
        calories: 450,
        rating: 4.8,
        reviewCount: 198,
        viewCount: 4500,
        soldCount: 560,
        discount: 0,
      },

      // KHAI VỊ
      {
        name: "Salad Caesar",
        description: "Rau xà lách tươi, phô mai Parmesan, sốt Caesar",
        price: 75000,
        categoryId: categories[1]._id,
        listProductImage: [images[0]._id],
        stock: 45,
        status: "available",
        preparationTime: "10-12 phút",
        calories: 280,
        rating: 4.5,
        reviewCount: 167,
        viewCount: 3200,
        soldCount: 420,
        discount: 0,
      },
      {
        name: "Gỏi cuốn tôm thịt",
        description: "Gỏi cuốn tươi ngon, tôm thịt đầy đủ",
        price: 55000,
        categoryId: categories[1]._id,
        listProductImage: [images[3]._id],
        stock: 60,
        status: "available",
        preparationTime: "8-10 phút",
        calories: 180,
        rating: 4.6,
        reviewCount: 234,
        viewCount: 4800,
        soldCount: 780,
        discount: 0,
      },
      {
        name: "Soup bí đỏ",
        description: "Soup bí đỏ béo ngậy, hạt điều rang",
        price: 45000,
        categoryId: categories[1]._id,
        listProductImage: [images[13]._id],
        stock: 0,
        status: "out_of_stock",
        preparationTime: "12-15 phút",
        calories: 220,
        rating: 4.4,
        reviewCount: 89,
        viewCount: 1500,
        soldCount: 180,
        discount: 0,
      },

      // TRÁNG MIỆNG
      {
        name: "Tiramisu Ý",
        description: "Bánh tiramisu truyền thống, cà phê Espresso",
        price: 65000,
        categoryId: categories[2]._id,
        listProductImage: [images[12]._id],
        stock: 25,
        status: "available",
        preparationTime: "5 phút",
        calories: 320,
        rating: 4.7,
        reviewCount: 156,
        viewCount: 3400,
        soldCount: 450,
        discount: 0,
      },
      {
        name: "Pancake dâu tây",
        description: "Bánh pancake xốp mềm, sốt dâu tây tươi",
        price: 55000,
        categoryId: categories[2]._id,
        listProductImage: [images[5]._id],
        stock: 35,
        status: "available",
        preparationTime: "12-15 phút",
        calories: 380,
        rating: 4.8,
        reviewCount: 289,
        viewCount: 6200,
        soldCount: 820,
        discount: 15,
      },
      {
        name: "Kem vanilla Madagascar",
        description: "Kem vanilla nguyên chất từ Madagascar",
        price: 42000,
        categoryId: categories[2]._id,
        listProductImage: [images[12]._id],
        stock: 50,
        status: "available",
        preparationTime: "3 phút",
        calories: 240,
        rating: 4.6,
        reviewCount: 178,
        viewCount: 4100,
        soldCount: 620,
        discount: 0,
      },

      // ĐỒ UỐNG
      {
        name: "Cà phê sữa đá Việt Nam",
        description: "Cà phê phin truyền thống, sữa đặc ngọt ngào",
        price: 35000,
        categoryId: categories[3]._id,
        listProductImage: [images[10]._id],
        stock: 100,
        status: "available",
        preparationTime: "5-7 phút",
        calories: 180,
        rating: 4.9,
        reviewCount: 567,
        viewCount: 12000,
        soldCount: 2300,
        discount: 0,
      },
      {
        name: "Sinh tố bơ",
        description: "Sinh tố bơ sánh mịn, bổ dưỡng",
        price: 45000,
        categoryId: categories[3]._id,
        listProductImage: [images[11]._id],
        stock: 80,
        status: "available",
        preparationTime: "5 phút",
        calories: 280,
        rating: 4.7,
        reviewCount: 412,
        viewCount: 8900,
        soldCount: 1450,
        discount: 0,
      },
      {
        name: "Trà sữa trân châu đường đen",
        description: "Trà sữa thơm ngon, trân châu mềm dẻo",
        price: 42000,
        categoryId: categories[3]._id,
        listProductImage: [images[10]._id],
        stock: 120,
        status: "available",
        preparationTime: "7-8 phút",
        calories: 320,
        rating: 4.8,
        reviewCount: 689,
        viewCount: 15000,
        soldCount: 2800,
        discount: 20,
      },
      {
        name: "Nước ép cam tươi",
        description: "Cam tươi vắt 100%, không đường",
        price: 38000,
        categoryId: categories[3]._id,
        listProductImage: [images[11]._id],
        stock: 0,
        status: "out_of_stock",
        preparationTime: "5 phút",
        calories: 120,
        rating: 4.6,
        reviewCount: 234,
        viewCount: 5200,
        soldCount: 980,
        discount: 0,
      },

      // SALAD
      {
        name: "Salad Hy Lạp",
        description: "Cà chua bi, dưa chuột, phô mai Feta, olive đen",
        price: 85000,
        categoryId: categories[4]._id,
        listProductImage: [images[6]._id],
        stock: 30,
        status: "available",
        preparationTime: "10 phút",
        calories: 240,
        rating: 4.7,
        reviewCount: 145,
        viewCount: 3100,
        soldCount: 380,
        discount: 0,
      },
      {
        name: "Salad rau củ quả hỗn hợp",
        description: "Rau củ quả tươi, sốt dầu olive",
        price: 70000,
        categoryId: categories[4]._id,
        listProductImage: [images[7]._id],
        stock: 40,
        status: "available",
        preparationTime: "8-10 phút",
        calories: 180,
        rating: 4.5,
        reviewCount: 178,
        viewCount: 3800,
        soldCount: 520,
        discount: 30,
      },

      // MÓN CHÍNH - Thêm mới
      {
        name: "Cơm tấm sườn nướng",
        description: "Cơm tấm thơm, sườn nướng mật ong, chả trứng",
        price: 95000,
        categoryId: categories[0]._id,
        listProductImage: [images[4]._id],
        stock: 55,
        status: "available",
        preparationTime: "18-22 phút",
        calories: 650,
        rating: 4.6,
        reviewCount: 423,
        viewCount: 7800,
        soldCount: 1100,
        discount: 10,
      },
      {
        name: "Phở bò tái chín",
        description: "Phở truyền thống, thịt bò tái chín, nước dùng đậm đà",
        price: 80000,
        categoryId: categories[0]._id,
        listProductImage: [images[13]._id],
        stock: 60,
        status: "available",
        preparationTime: "12-15 phút",
        calories: 480,
        rating: 4.8,
        reviewCount: 512,
        viewCount: 9500,
        soldCount: 1350,
        discount: 0,
      },
      {
        name: "Bún chả Hà Nội",
        description: "Bún chả truyền thống, thịt nướng thơm lừng",
        price: 75000,
        categoryId: categories[0]._id,
        listProductImage: [images[3]._id],
        stock: 50,
        status: "available",
        preparationTime: "15-18 phút",
        calories: 420,
        rating: 4.7,
        reviewCount: 389,
        viewCount: 8200,
        soldCount: 980,
        discount: 15,
      },
      {
        name: "Pizza Pepperoni",
        description: "Pizza với pepperoni cay, phô mai Mozzarella tan chảy",
        price: 195000,
        categoryId: categories[0]._id,
        listProductImage: [images[1]._id],
        stock: 28,
        status: "available",
        preparationTime: "20-25 phút",
        calories: 720,
        rating: 4.6,
        reviewCount: 234,
        viewCount: 6500,
        soldCount: 720,
        discount: 20,
      },
      {
        name: "Pizza Hải sản",
        description: "Pizza với tôm, mực, cá hồi tươi ngon",
        price: 220000,
        categoryId: categories[0]._id,
        listProductImage: [images[1]._id],
        stock: 25,
        status: "available",
        preparationTime: "22-28 phút",
        calories: 680,
        rating: 4.7,
        reviewCount: 198,
        viewCount: 5800,
        soldCount: 650,
        discount: 0,
      },
      {
        name: "Pasta Bolognese",
        description: "Mì Ý sốt thịt bò băm, cà chua tươi",
        price: 135000,
        categoryId: categories[0]._id,
        listProductImage: [images[8]._id],
        stock: 32,
        status: "available",
        preparationTime: "18-22 phút",
        calories: 620,
        rating: 4.5,
        reviewCount: 267,
        viewCount: 5900,
        soldCount: 780,
        discount: 15,
      },
      {
        name: "Pasta Marinara",
        description: "Mì Ý sốt cà chua tươi, tỏi, húng quế",
        price: 110000,
        categoryId: categories[0]._id,
        listProductImage: [images[8]._id],
        stock: 38,
        status: "available",
        preparationTime: "15-18 phút",
        calories: 480,
        rating: 4.4,
        reviewCount: 189,
        viewCount: 4200,
        soldCount: 540,
        discount: 0,
      },
      {
        name: "Cơm chiên Dương Châu",
        description: "Cơm chiên với tôm, thịt, trứng, rau củ",
        price: 90000,
        categoryId: categories[0]._id,
        listProductImage: [images[4]._id],
        stock: 45,
        status: "available",
        preparationTime: "15-20 phút",
        calories: 580,
        rating: 4.6,
        reviewCount: 312,
        viewCount: 6800,
        soldCount: 890,
        discount: 10,
      },
      {
        name: "Bánh mì thịt nướng",
        description: "Bánh mì giòn, thịt nướng thơm, pate, rau củ",
        price: 55000,
        categoryId: categories[0]._id,
        listProductImage: [images[2]._id],
        stock: 70,
        status: "available",
        preparationTime: "8-10 phút",
        calories: 420,
        rating: 4.8,
        reviewCount: 678,
        viewCount: 11200,
        soldCount: 1890,
        discount: 0,
      },
      {
        name: "Bánh xèo tôm thịt",
        description: "Bánh xèo giòn, tôm thịt đầy đủ, rau sống",
        price: 70000,
        categoryId: categories[0]._id,
        listProductImage: [images[3]._id],
        stock: 40,
        status: "available",
        preparationTime: "12-15 phút",
        calories: 450,
        rating: 4.7,
        reviewCount: 445,
        viewCount: 7800,
        soldCount: 1120,
        discount: 0,
      },
      {
        name: "Cá hồi nướng sốt teriyaki",
        description: "Cá hồi tươi nướng, sốt teriyaki ngọt đậm đà",
        price: 280000,
        categoryId: categories[0]._id,
        listProductImage: [images[9]._id],
        stock: 18,
        status: "available",
        preparationTime: "20-25 phút",
        calories: 520,
        rating: 4.9,
        reviewCount: 234,
        viewCount: 5200,
        soldCount: 450,
        discount: 0,
      },
      {
        name: "Gà nướng mật ong",
        description: "Gà nguyên con nướng mật ong, thơm lừng",
        price: 320000,
        categoryId: categories[0]._id,
        listProductImage: [images[4]._id],
        stock: 15,
        status: "available",
        preparationTime: "35-40 phút",
        calories: 780,
        rating: 4.7,
        reviewCount: 178,
        viewCount: 4100,
        soldCount: 320,
        discount: 25,
      },
      {
        name: "Lẩu Thái chua cay",
        description: "Lẩu Thái đậm đà, tôm cá tươi, rau củ",
        price: 350000,
        categoryId: categories[0]._id,
        listProductImage: [images[13]._id],
        stock: 12,
        status: "available",
        preparationTime: "30 phút",
        calories: 450,
        rating: 4.8,
        reviewCount: 156,
        viewCount: 3800,
        soldCount: 280,
        discount: 0,
      },
      {
        name: "Bánh mì kẹp thịt nướng",
        description: "Burger Việt Nam, thịt nướng đậm đà",
        price: 65000,
        categoryId: categories[0]._id,
        listProductImage: [images[2]._id],
        stock: 55,
        status: "available",
        preparationTime: "10-12 phút",
        calories: 480,
        rating: 4.6,
        reviewCount: 389,
        viewCount: 7200,
        soldCount: 980,
        discount: 0,
      },

      // KHAI VỊ - Thêm mới
      {
        name: "Nem nướng Nha Trang",
        description: "Nem nướng thơm lừng, chấm mắm nêm",
        price: 65000,
        categoryId: categories[1]._id,
        listProductImage: [images[3]._id],
        stock: 50,
        status: "available",
        preparationTime: "12-15 phút",
        calories: 320,
        rating: 4.7,
        reviewCount: 289,
        viewCount: 5600,
        soldCount: 720,
        discount: 0,
      },
      {
        name: "Chả giò",
        description: "Chả giò giòn rụm, nhân tôm thịt đầy đủ",
        price: 60000,
        categoryId: categories[1]._id,
        listProductImage: [images[3]._id],
        stock: 55,
        status: "available",
        preparationTime: "10-12 phút",
        calories: 280,
        rating: 4.6,
        reviewCount: 312,
        viewCount: 6100,
        soldCount: 890,
        discount: 10,
      },
      {
        name: "Soup cua",
        description: "Soup cua béo ngậy, thịt cua tươi",
        price: 50000,
        categoryId: categories[1]._id,
        listProductImage: [images[13]._id],
        stock: 40,
        status: "available",
        preparationTime: "15-18 phút",
        calories: 240,
        rating: 4.5,
        reviewCount: 198,
        viewCount: 3800,
        soldCount: 540,
        discount: 0,
      },
      {
        name: "Soup gà nấm",
        description: "Soup gà nấm thơm ngon, bổ dưỡng",
        price: 48000,
        categoryId: categories[1]._id,
        listProductImage: [images[13]._id],
        stock: 45,
        status: "available",
        preparationTime: "12-15 phút",
        calories: 200,
        rating: 4.4,
        reviewCount: 167,
        viewCount: 3200,
        soldCount: 420,
        discount: 0,
      },
      {
        name: "Bánh mì pate",
        description: "Bánh mì giòn, pate thơm, chả lụa",
        price: 35000,
        categoryId: categories[1]._id,
        listProductImage: [images[2]._id],
        stock: 80,
        status: "available",
        preparationTime: "5 phút",
        calories: 280,
        rating: 4.5,
        reviewCount: 456,
        viewCount: 8900,
        soldCount: 1450,
        discount: 0,
      },
      {
        name: "Salad tôm",
        description: "Salad tươi, tôm nướng, sốt chua ngọt",
        price: 85000,
        categoryId: categories[1]._id,
        listProductImage: [images[0]._id],
        stock: 35,
        status: "available",
        preparationTime: "10-12 phút",
        calories: 260,
        rating: 4.6,
        reviewCount: 234,
        viewCount: 4800,
        soldCount: 560,
        discount: 15,
      },
      {
        name: "Bánh mì chả cá",
        description: "Bánh mì chả cá Nha Trang, rau sống",
        price: 45000,
        categoryId: categories[1]._id,
        listProductImage: [images[2]._id],
        stock: 60,
        status: "available",
        preparationTime: "8-10 phút",
        calories: 320,
        rating: 4.7,
        reviewCount: 345,
        viewCount: 6800,
        soldCount: 980,
        discount: 0,
      },

      // TRÁNG MIỆNG - Thêm mới
      {
        name: "Bánh flan caramel",
        description: "Bánh flan mềm mịn, sốt caramel ngọt ngào",
        price: 45000,
        categoryId: categories[2]._id,
        listProductImage: [images[12]._id],
        stock: 40,
        status: "available",
        preparationTime: "3 phút",
        calories: 280,
        rating: 4.6,
        reviewCount: 234,
        viewCount: 4800,
        soldCount: 650,
        discount: 0,
      },
      {
        name: "Chè đậu xanh",
        description: "Chè đậu xanh mát lạnh, nước cốt dừa",
        price: 35000,
        categoryId: categories[2]._id,
        listProductImage: [images[12]._id],
        stock: 60,
        status: "available",
        preparationTime: "5 phút",
        calories: 220,
        rating: 4.5,
        reviewCount: 312,
        viewCount: 6200,
        soldCount: 890,
        discount: 0,
      },
      {
        name: "Chè khúc bạch",
        description: "Chè khúc bạch mát lạnh, thạch dừa",
        price: 40000,
        categoryId: categories[2]._id,
        listProductImage: [images[12]._id],
        stock: 50,
        status: "available",
        preparationTime: "5 phút",
        calories: 240,
        rating: 4.7,
        reviewCount: 267,
        viewCount: 5400,
        soldCount: 720,
        discount: 10,
      },
      {
        name: "Bánh chocolate lava",
        description: "Bánh chocolate nóng chảy, kem vani",
        price: 75000,
        categoryId: categories[2]._id,
        listProductImage: [images[12]._id],
        stock: 25,
        status: "available",
        preparationTime: "15-18 phút",
        calories: 420,
        rating: 4.8,
        reviewCount: 189,
        viewCount: 4100,
        soldCount: 450,
        discount: 0,
      },
      {
        name: "Kem matcha",
        description: "Kem matcha Nhật Bản, đậm đà",
        price: 50000,
        categoryId: categories[2]._id,
        listProductImage: [images[12]._id],
        stock: 45,
        status: "available",
        preparationTime: "3 phút",
        calories: 260,
        rating: 4.7,
        reviewCount: 223,
        viewCount: 4900,
        soldCount: 580,
        discount: 0,
      },
      {
        name: "Bánh crepe sầu riêng",
        description: "Bánh crepe mỏng, sầu riêng thơm lừng",
        price: 60000,
        categoryId: categories[2]._id,
        listProductImage: [images[5]._id],
        stock: 30,
        status: "available",
        preparationTime: "10-12 phút",
        calories: 380,
        rating: 4.6,
        reviewCount: 178,
        viewCount: 3600,
        soldCount: 420,
        discount: 15,
      },
      {
        name: "Bánh bông lan trứng muối",
        description: "Bánh bông lan mềm, trứng muối béo ngậy",
        price: 55000,
        categoryId: categories[2]._id,
        listProductImage: [images[12]._id],
        stock: 35,
        status: "available",
        preparationTime: "8-10 phút",
        calories: 340,
        rating: 4.5,
        reviewCount: 145,
        viewCount: 3100,
        soldCount: 380,
        discount: 0,
      },
      {
        name: "Kem dừa",
        description: "Kem dừa tươi mát, cốt dừa béo ngậy",
        price: 40000,
        categoryId: categories[2]._id,
        listProductImage: [images[12]._id],
        stock: 55,
        status: "available",
        preparationTime: "3 phút",
        calories: 220,
        rating: 4.6,
        reviewCount: 267,
        viewCount: 5800,
        soldCount: 780,
        discount: 0,
      },

      // ĐỒ UỐNG - Thêm mới
      {
        name: "Cà phê đen đá",
        description: "Cà phê phin đậm đà, không đường",
        price: 30000,
        categoryId: categories[3]._id,
        listProductImage: [images[10]._id],
        stock: 120,
        status: "available",
        preparationTime: "5-7 phút",
        calories: 5,
        rating: 4.7,
        reviewCount: 423,
        viewCount: 9800,
        soldCount: 1650,
        discount: 0,
      },
      {
        name: "Cà phê cappuccino",
        description: "Cà phê espresso, sữa nóng, bọt sữa",
        price: 55000,
        categoryId: categories[3]._id,
        listProductImage: [images[10]._id],
        stock: 90,
        status: "available",
        preparationTime: "8-10 phút",
        calories: 120,
        rating: 4.6,
        reviewCount: 312,
        viewCount: 7200,
        soldCount: 980,
        discount: 0,
      },
      {
        name: "Cà phê latte",
        description: "Cà phê espresso, sữa nóng, nghệ thuật latte",
        price: 60000,
        categoryId: categories[3]._id,
        listProductImage: [images[10]._id],
        stock: 85,
        status: "available",
        preparationTime: "8-10 phút",
        calories: 150,
        rating: 4.7,
        reviewCount: 289,
        viewCount: 6800,
        soldCount: 850,
        discount: 10,
      },
      {
        name: "Sinh tố dâu tây",
        description: "Sinh tố dâu tây tươi, sữa chua",
        price: 50000,
        categoryId: categories[3]._id,
        listProductImage: [images[11]._id],
        stock: 75,
        status: "available",
        preparationTime: "5 phút",
        calories: 240,
        rating: 4.6,
        reviewCount: 345,
        viewCount: 7800,
        soldCount: 1120,
        discount: 0,
      },
      {
        name: "Sinh tố xoài",
        description: "Sinh tố xoài chín, sữa đặc",
        price: 48000,
        categoryId: categories[3]._id,
        listProductImage: [images[11]._id],
        stock: 80,
        status: "available",
        preparationTime: "5 phút",
        calories: 260,
        rating: 4.7,
        reviewCount: 389,
        viewCount: 8200,
        soldCount: 1250,
        discount: 0,
      },
      {
        name: "Nước ép dưa hấu",
        description: "Dưa hấu tươi ép 100%, mát lạnh",
        price: 40000,
        categoryId: categories[3]._id,
        listProductImage: [images[11]._id],
        stock: 90,
        status: "available",
        preparationTime: "5 phút",
        calories: 100,
        rating: 4.5,
        reviewCount: 234,
        viewCount: 5600,
        soldCount: 780,
        discount: 15,
      },
      {
        name: "Nước ép táo",
        description: "Táo tươi ép 100%, không đường",
        price: 42000,
        categoryId: categories[3]._id,
        listProductImage: [images[11]._id],
        stock: 85,
        status: "available",
        preparationTime: "5 phút",
        calories: 110,
        rating: 4.6,
        reviewCount: 267,
        viewCount: 6100,
        soldCount: 890,
        discount: 0,
      },
      {
        name: "Trà đào cam sả",
        description: "Trà đào thơm, cam sả mát lạnh",
        price: 45000,
        categoryId: categories[3]._id,
        listProductImage: [images[10]._id],
        stock: 100,
        status: "available",
        preparationTime: "7-8 phút",
        calories: 140,
        rating: 4.8,
        reviewCount: 512,
        viewCount: 11200,
        soldCount: 1890,
        discount: 0,
      },
      {
        name: "Trà sữa matcha",
        description: "Trà matcha đậm đà, sữa tươi, trân châu",
        price: 50000,
        categoryId: categories[3]._id,
        listProductImage: [images[10]._id],
        stock: 95,
        status: "available",
        preparationTime: "7-8 phút",
        calories: 280,
        rating: 4.7,
        reviewCount: 445,
        viewCount: 9800,
        soldCount: 1350,
        discount: 10,
      },
      {
        name: "Soda chanh dây",
        description: "Soda mát lạnh, chanh dây chua ngọt",
        price: 38000,
        categoryId: categories[3]._id,
        listProductImage: [images[10]._id],
        stock: 110,
        status: "available",
        preparationTime: "5 phút",
        calories: 120,
        rating: 4.5,
        reviewCount: 312,
        viewCount: 7200,
        soldCount: 980,
        discount: 0,
      },

      // SALAD - Thêm mới
      {
        name: "Salad cá ngừ",
        description: "Salad tươi, cá ngừ nướng, sốt mật ong",
        price: 95000,
        categoryId: categories[4]._id,
        listProductImage: [images[6]._id],
        stock: 25,
        status: "available",
        preparationTime: "12-15 phút",
        calories: 320,
        rating: 4.7,
        reviewCount: 189,
        viewCount: 4200,
        soldCount: 450,
        discount: 0,
      },
      {
        name: "Salad gà nướng",
        description: "Salad tươi, gà nướng mật ong, sốt chua ngọt",
        price: 90000,
        categoryId: categories[4]._id,
        listProductImage: [images[6]._id],
        stock: 30,
        status: "available",
        preparationTime: "10-12 phút",
        calories: 380,
        rating: 4.6,
        reviewCount: 234,
        viewCount: 4800,
        soldCount: 560,
        discount: 15,
      },
      {
        name: "Salad trái cây",
        description: "Salad trái cây tươi, sốt sữa chua",
        price: 80000,
        categoryId: categories[4]._id,
        listProductImage: [images[7]._id],
        stock: 40,
        status: "available",
        preparationTime: "8-10 phút",
        calories: 200,
        rating: 4.5,
        reviewCount: 178,
        viewCount: 3800,
        soldCount: 480,
        discount: 0,
      },
      {
        name: "Salad quinoa",
        description: "Salad quinoa, rau củ, sốt dầu olive",
        price: 100000,
        categoryId: categories[4]._id,
        listProductImage: [images[7]._id],
        stock: 28,
        status: "available",
        preparationTime: "12-15 phút",
        calories: 280,
        rating: 4.6,
        reviewCount: 145,
        viewCount: 3200,
        soldCount: 380,
        discount: 20,
      },
      {
        name: "Salad bắp cải tím",
        description: "Salad bắp cải tím, cà rốt, sốt chua ngọt",
        price: 75000,
        categoryId: categories[4]._id,
        listProductImage: [images[0]._id],
        stock: 45,
        status: "available",
        preparationTime: "8-10 phút",
        calories: 160,
        rating: 4.4,
        reviewCount: 123,
        viewCount: 2800,
        soldCount: 320,
        discount: 0,
      },
    ];

    await Product.insertMany(productsData);
    
    console.log(`✅ Đã tạo ${productsData.length} products`);
    console.log("\n📊 THỐNG KÊ:");
    console.log(`   - Có khuyến mãi: ${productsData.filter(p => p.discount > 0).length}`);
    console.log(`   - Hết hàng: ${productsData.filter(p => p.stock === 0).length}`);
    console.log(`   - Best sellers (sold > 1000): ${productsData.filter(p => p.soldCount > 1000).length}`);
    console.log(`   - Highest rated (4.8+): ${productsData.filter(p => p.rating >= 4.8).length}`);

  } catch (error) {
    console.error("❌ Lỗi:", error);
  }
};

const main = async () => {
  await connectDB();
  await seedData();
  console.log("\n✅ HOÀN TẤT!");
  process.exit(0);
};

main();